### ISSUE TITLE
Not enough men :((((((((

### ISSUE THREAD

**Issue by esk33** [Men-3/Men-bot-videogame#1]
will fix soon ;)

**Comment by gom4n** [comment]
suck these nuts

**Comment by esk33** [comment]
> suck these nuts

yes please daddy max please let me suck your nuts please please please please please

**Comment by tnix100** [comment]
still not enough men

**Comment by esk33** [comment]
agreed.

**Comment by tnix100** [comment]
good.

**Comment by gom4n** [comment]
i added 3 more men to the men

**Comment by tnix100** [comment]
> i added 3 more men to the men

thank you, much appreciated
