### ISSUE TITLE
README contains untrue content, and other files too

### ISSUE THREAD

**Issue by theycallhermax** [Men-3/Men-bot-videogame#5]
<sup>Oh boy, this is going to be a long one.</sup>
1. Building section in README has nothing about building it
2. Cloning on Windows is just basically a loop
3. Cloning on Linux is basically a script to shut down Linux, and doing magic, as in shutting down the computer, sex.sh does the same thing
4. Cloning your mother makes no sense, and, just for clarification, Python 3 is not compatible with Windows 95, and the pip command seems incorrect, as it would be pip3.
5. Some parts make no sense in the main file, or is inappropriate.

**Comment by gom4n** [comment]
are you mentally stable this is a shitpost

**Comment by theycallhermax** [comment]
> are you mentally stable this is a shitpost

No, I'm not. I'm a escaped hospital patient who was undergoing brain surgery.

**Comment by tnix100** [comment]
Seems everything that was addressed has been fixed.
