### ISSUE TITLE
extension

### ISSUE THREAD

**Issue by tnix100** [Men-3/Men-bot-videogame#8]
I think this project needs an extension until 2181, at this rate we won't finish by 2048

**Comment by gom4n** [comment]
no

**Comment by tnix100** [comment]
> no

guess we'll just have to rush some features then, like mother bossfight or mother cloning technology

**Comment by tnix100** [comment]
> the complete mother bossfight path should be finished in 20 years or so, so not much wiggle room

exactly, and max won't give us the extension, so unfair

**Comment by gom4n** [comment]
ive given you 4 year leave already hayden

**Comment by tnix100** [comment]
hello goman

**Comment by gom4n** [comment]
no
